"""Update cart db

Revision ID: 03055c8bc51c
Revises: 13f7474c5c21
Create Date: 2023-03-14 22:30:55.296348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03055c8bc51c'
down_revision = '13f7474c5c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_list', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
