"""Update cart db

Revision ID: fff980d12f86
Revises: 03055c8bc51c
Create Date: 2023-03-14 23:17:56.765293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff980d12f86'
down_revision = '03055c8bc51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_list', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
